
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-15
owner: ucsb-cs156-s25
repo_name: team02-s25-15
pull_requests: [{"author":{"id":"U_kgDOCM79zg","is_bot":false,"login":"Tyler-W0ng","name":""},"headRefName":"tw-MenuItemReview-table","number":68,"title":"Tw menu item review table","url":"https://github.com/ucsb-cs156-s25/team02-s25-15/pull/68"},{"author":{"id":"U_kgDOCVG6FA","is_bot":false,"login":"BryceInouye","name":""},"headRefName":"bi-articles-form-component","number":67,"title":"Bi articles form component","url":"https://github.com/ucsb-cs156-s25/team02-s25-15/pull/67"},{"author":{"id":"U_kgDOCM79zg","is_bot":false,"login":"Tyler-W0ng","name":""},"headRefName":"tw-MenuItemReview-form","number":66,"title":"Tw menu item review form","url":"https://github.com/ucsb-cs156-s25/team02-s25-15/pull/66"},{"author":{"id":"U_kgDOCVG6FA","is_bot":false,"login":"BryceInouye","name":""},"headRefName":"bi-articles-backend","number":63,"title":"bi - Copy files for Backend CRUD API Articles from team02","url":"https://github.com/ucsb-cs156-s25/team02-s25-15/pull/63"},{"author":{"id":"U_kgDOCM79zg","is_bot":false,"login":"Tyler-W0ng","name":""},"headRefName":"tw-MenuItemReview-fixture","number":62,"title":"Tw menu item review fixture","url":"https://github.com/ucsb-cs156-s25/team02-s25-15/pull/62"},{"author":{"id":"U_kgDOCM79zg","is_bot":false,"login":"Tyler-W0ng","name":""},"headRefName":"tw-copy-backend-for-MenuItemReviews","number":61,"title":"Add MenuItemReview controller, entity, repo, test, and migration","url":"https://github.com/ucsb-cs156-s25/team02-s25-15/pull/61"}]
