
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-15
owner: ucsb-cs156-s25
repo_name: team02-s25-15
pull_requests: [{"author":{"id":"U_kgDOCJYDtQ","is_bot":false,"login":"Esomevath","name":"Lucas Havemose"},"headRefName":"lh-UCSBDiningCommonsMenuItem-end2end-tests","number":126,"title":"UCSBDiningCommonsMenuItem end to end tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-15/pull/126"},{"author":{"id":"U_kgDOCJYDtQ","is_bot":false,"login":"Esomevath","name":"Lucas Havemose"},"headRefName":"lh-UCSBDiningCommonsMenuItem-integration-tests","number":125,"title":"UCSBDiningCommonsMenuItem integration tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-15/pull/125"},{"author":{"id":"MDQ6VXNlcjg1MDA2ODI4","is_bot":false,"login":"perryjirakit","name":""},"headRefName":"pt-create-RecommendationRequest-page","number":123,"title":"pt - create recommendation request page","url":"https://github.com/ucsb-cs156-s25/team02-s25-15/pull/123"},{"author":{"id":"U_kgDOB9EidQ","is_bot":false,"login":"davidduena","name":""},"headRefName":"dd-helprequest-edit-page","number":110,"title":"Dd- helprequest edit page","url":"https://github.com/ucsb-cs156-s25/team02-s25-15/pull/110"},{"author":{"id":"U_kgDOCVHkAA","is_bot":false,"login":"yuecao365","name":""},"headRefName":"yc-UCSBOrganization-edit-page","number":99,"title":"Yc ucsb organization edit page","url":"https://github.com/ucsb-cs156-s25/team02-s25-15/pull/99"}]
